flask/day04/app/models.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

class Student(db.Model):
    id = db.Column(db.Integer,primary_key=True,autoincrement=True)
    s_name = db.Column(db.String(10),unique=True,nullable=False)
    gender = db.Column(db.Boolean,default=1)
    grade_id = db.Column(db.Integer,db.ForeignKey('grade.id'),nullable=True)

    # __tablename__ 要不高于指定模型映射的表名，如果没有指定，则表名为模型名的小写

    def save(self):
        db.session.add(self)
        db.session.commit()

class Grade(db.Model):
    id = db.Column(db.Integer,primary_key=True,autoincrement=True)
    g_name = db.Column(db.String(10),nullable=True,unique=True)
    student = db.relationship('Student',backref='g')


s_c = db.Table('s_c',
               db.Column('s_id',db.Integer,db.ForeignKey('student.id')),
               db.Column('c_id',db.Integer,db.ForeignKey('course.id')),
            )
class Course(db.Model):

    id = db.Column(db.Integer,primary_key=True,autoincrement=True)
    c_name = db.Column(db.String(10),nullable=False,unique=True)
    student = db.relationship('Student',secondary=s_c,backref='cou')

    __tablename__ = 'course'

flask/day04/app/views.py
from flask import Blueprint, render_template, \
    request, url_for,redirect,jsonify
from sqlalchemy import and_,not_,or_
from app.models import db, Student, Grade, Course

blue = Blueprint('app',__name__)

# @blue.route('/')
# def hello():
#     return 'hello'



@blue.route('/create_db/')
def create_db():
    db.create_all()
    return '创建成功'

@blue.route('/add_stu/',methods=['POST'])
def add_stu():
    #插入数据
    stu = Student()
    stu.s_name = '咻咻'
    # db.session.add(stu)
    # db.session.commit()
    stu.save()
    return '创建学生成功'

@blue.route('/del_stu/',methods=['DELETE'])
def del_stu():
    #删除数据
    stu = Student.query.filter(Student.s_name == '咻咻').first()
    db.session.delete(stu)
    db.session.commit()
    return '删除学生成功'

@blue.route('/up_stu/',methods=['PATCH'])
def up_stu():
    #第一种方式
    # stu = Student.query.filter(Student.s_name == '笑笑').first()
    # stu.s_name = '大傻子'
    # stu.save()
    #第二种方法
    Student.query.filter(Student.s_name == '大傻子').update({'s_name':'二傻子'})
    db.session.commit()

    return '更新成功'

@blue.route('/sel_stu/',methods=['GET'])
def sel_stu():
    # filter(模型名，字段 == '值')
    #filter_by(字段 = '值')
    stu = Student.query.filter_by(s_name='二傻子').first()
    # all():查询所有的结果，返回结果列表
    # first():返回对象
    # 注意：不要写all().first()



    # stu = Student.query.filter(Student.id == 1).first()
    # 查询id为1的学生，使用get()方法
    # get():get获取主键所在行的对象，如果获取不到返回空
    stu = Student.query.get(1)

    #order_by():排序
    # 降序：-id,id desc
    # 升序：id,id asc
    stu = Student.query.order_by('-id')

    #使用运算符
    # Django的ORM中:filter(s_name__contains = '111')
    # Flask的SQLAlchemy中：filter(模型名.s_name.contains(''))

    #例：模糊查询学生中包含'三'的学生信息,contains
    # stus = Student.query.filter(Student.s_name.contains('三')).all()

    #startwith,endswith,like _和%,contains

    stus = Student.query.filter(Student.s_name.startswith('二')).all()
    stus = Student.query.filter(Student.s_name.endswith('子')).all()
    #包含张
    stus = Student.query.filter(Student.s_name.like('%张%')).all()
    #第二个字是张
    stus = Student.query.filter(Student.s_name.like('_张%')).all()
    #第一个字为张
    stus = Student.query.filter(Student.s_name.like('张%')).all()
    stus = Student.query.filter(Student.s_name.like('%张')).all()
    #in_():查询某个范围之内的对象
    stus = Student.query.filter(Student.id.in_([1,2,3,4,5])).all()

    #查询id大于3的学生信息，__gt__
    # 大于 __gt__,大于等于 __ge__
    # 小于 __lt__,小于等于 __le__
    stus = Student.query.filter(Student.id.__gt__(3)).all()
    stus = Student.query.filter(Student.id > 3).all()

    #分页
    page = request.args.get('page',1)
    paginate = Student.query.paginate(int(page),3)
    stus = paginate.items

    # return render_template('stus.html',stus=stus,paginate=paginate)

    #查询性别为男，且姓名中包含'子'的学生信息
    stus = Student.query.filter(Student.gender == 1,
                                Student.s_name.contains('子')).all()

    # and_且, not_非, or_或
    stus = Student.query.filter(and_(Student.gender == 1,
                                Student.s_name.contains('子'))).all()

    stus = Student.query.filter(or_(Student.gender == 1,
                                Student.s_name.contains('成'))).all()

    stus = Student.query.filter(not_(Student.gender == 1),
                                and_(Student.s_name.contains('大'))).all()


    stus_names = [stu.s_name for stu in stus]
    return str(stus_names)

# 添加班级信息
@blue.route('/add_grade/',methods=['POST'])
def add_grade():
    grades = ['大一','大二','大三','大四']
    g_list = []
    for i in grades:
        g = Grade()
        g.g_name = i
        # db.session.add(g)
        g_list.append(g)
    db.session.add_all(g_list)
    db.session.commit()
    return '创建班级成功'

# 学生指定班级


#作业：
#正向查询：通过学生查找班级
@blue.route('/select_gda/',methods=['GET'])
def select_gda():
    #通过学生查询班级
    stu = Student.query.filter(Student.s_name=='大傻子').first()
    # 学生对象backref
    grade = stu.g
    return '查询成功'
    # return render_template('base.html',grade=grade,stu=stu)
#反向查询：通过班级查找学生
@blue.route('/select_stu/',methods=['GET'])
def select_stu():
    grade = Grade.query.get(3)
    stus = grade.student
    return '查询成功'
    # return render_template('students.html',stus=stus,grade=grade)


@blue.route('/add_course/', methods=['POST'])
def add_course():
    cou = Course()
    cou.c_name = '大学英语'
    db.session.add(cou)
    db.session.commit()

    return '创建成功'


@blue.route('/all_stu/',methods=['GET'])
def all_stu():
    stus = Student.query.all()
    return render_template('students.html',stus=stus)

@blue.route('/cous/<int:id>',methods=['GET','POST'])
def cous(id):
    if request.method == 'GET':
        cous = Course.query.all()
        return render_template('cous.html',cous=cous)

    if request.method == 'POST':
        # 向中间表s_c中加入数据
        cou_id = request.form.get('cou.id')
        s_id = id
        # 获取对象
        stu = Student.query.get(s_id)
        cou = Course.query.get(cou_id)
        #关系指定
        stu.cou.append(cou)
        # cou.student.append(stu)
        db.session.commit()

        return redirect(url_for('app.all_stu'))


@blue.route('/del_stu_cou/<int:id>/',methods=['GET','DELETE'])
def del_stu_cou(id):
    if request.method == 'GET':
        stu = Student.query.get(id)
        cous = stu.cou
        return render_template('s_c.html',cous=cous,s_id=id)

    if request.method == 'DELETE':
        c_id = request.form.get('c_id')
        s_id = request.form.get('s_id')
        #获取对象
        stu = Student.query.get(s_id)
        cou = Course.query.get(c_id)
        #删除学生和课程的关联关系
        stu.cou.remove(cou)
        db.session.commit()
        return jsonify({'code':200,'msg':'请求成功'})


#django中的中间件：
# process_request
# process_view
# process_template_response
# process_exception
# process_response


# 钩子函数
# G
@blue.before_request
def before_request():
    print('before_request')


@blue.before_request
def before1_request():
    print('before1_request')


@blue.after_request
def after_request(response):
    print('after_request')
    return response


@blue.teardown_request
def teardown_request(exception):
    print('teardown_request')

flask/day04/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>

    {% block css %}
    {% endblock %}

    {% block js %}
    {% endblock %}
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

flask/day04/templates/cous.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post">
        <select name="cou.id">
            {% for cou in cous %}
                <option value="{{ cou.id }}">{{ cou.c_name }}</option>
            {% endfor %}
        </select>
        <input type="submit" value="提交">
    </form>
{% endblock %}

flask/day04/templates/s_c.html
{% extends 'base.html' %}


{% block js %}
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script>
        function del_cou(c_id,s_id){
            $.ajax({
                url: '/app/del_stu_cou/' + s_id + '/',
                dataType:'json',
                type:'DELETE',
                data:{'c_id':c_id,'s_id':s_id},
                success:function(data){
                    if(data.code == '200'){
                        location.href='/app/all_stu/'
                    }
                },
                error:function(data){
                    alert('删除失败')
                }
            })
        }
    </script>

{% endblock %}

{% block content %}
    {% for c in cous %}
        <p>
            {{ c.c_name }}
            <a onclick="del_cou({{ c.id }},{{ s_id }})">删除</a>
        </p>
    {% endfor %}
{% endblock %}

flask/day04/templates/students.html
{% extends 'base.html' %}

{% block content %}

    <table>
        <thead>
            <th>id</th>
            <th>姓名</th>
            <th>班级</th>
            <th>课程</th>
            <th>操作</th>
        </thead>
        <tbody>
            {% for stu in stus %}
                <tr>
                    <td>{{ stu.id }}</td>
                    <td>{{ stu.s_name }}</td>
                    <td>{{ stu.g.g_name }}</td>
                    <td>
                        {% for c in stu.cou %}
                            {{ c.c_name }}
                        {% endfor %}
                    </td>
                    <td>
                        <a href="{{ url_for('app.cous', id=stu.id) }}">添加学生课程</a>
                        |
                        <a href="{{ url_for('app.del_stu_cou', id=stu.id) }}">删除课程</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

flask/day04/templates/stus.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>学生信息</title>
</head>
<body>
    {% for stu in stus %}
        <p>id: {{ stu.id }} 姓名:{{ stu.s_name }}</p>
    {% endfor %}
    当前一共{{ paginate.pages }}页
    {% if paginate.has_prev %}
        <a href="{{ url_for('app.sel_stu') }}?page={{ paginate.prev_num }}">上一页</a>
    {% endif %}

    {% for i in paginate.iter_pages() %}
        <a href="{{ url_for('app.sel_stu') }}?page={{ i }}">{{ i }}</a>
    {% endfor %}

    {% if paginate.has_next %}
        <a href="{{ url_for('app.sel_stu') }}?page={{ paginate.next_num }}">下一页</a>
    {% endif %}


</body>
</html>