fresh_shop/cart/urls.py
from django.conf.urls import url
from cart import views

urlpatterns =[
    #加入购物车
    url(r'^add_cart/',views.add_cart,name='add_cart'),
    #购物车
    url(r'^cart/',views.cart,name='cart'),
    #结算
    url(r'^place_order',views.place_order,name='place_order'),
    #刷新价格
    url(r'^f_price/',views.f_price,name='f_price'),
    #购物车数据
    url(r'^cart_count/',views.cart_count,name='cart_count'),
    #修改购物车中商品个数
    url(r'^change_goods_num/',views.change_goods_num,name='change_goods_num'),
    #删除购物车中商品
    url(r'^del_goods/',views.del_goods,name='del_goods'),

]

fresh_shop/fresh_shop/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.staticfiles.urls import static

from fresh_shop.settings import MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^goods/',include('goods.urls',namespace='goods')),
    url(r'^user/',include('user.urls',namespace='user')),
    url(r'^cart/',include('cart.urls',namespace='cart')),
    url(r'^order/', include('order.urls', namespace='order')),
]
urlpatterns += static(MEDIA_URL,document_root=MEDIA_ROOT)

fresh_shop/goods/urls.py
from django.conf.urls import url
from goods import views

urlpatterns = [
    url(r'^index/',views.index,name='index'),
    #商品详情
    url(r'^detail/(\d+)/',views.detail,name='detail'),


]

fresh_shop/order/urls.py
from django.conf.urls import url
from order import views
urlpatterns = [
    #下单
    url(r'^order/',views.order,name='order'),
    #订单中心
    url(r'^user_order/',views.user_order,name='user_order'),
    #收货地址
    url(r'^user_order_site/',views.user_order_site,name='user_order_site'),

]

fresh_shop/user/urls.py
from django.conf.urls import url
from user import views

urlpatterns = [
    #注册
    url(r'^register/', views.register, name='register'),
    #登录
    url(r'^login/',views.login,name='login'),
    #注销
    url(r'^logout/', views.logout, name='logout'),
    #登录验证，获取登录系统的用户
    url(r'^is_login/',views.is_login,name='is_login'),
    #个人信息中心
    url(r'^user_center_order/',views.user_center_order,name='user_center_order'),
    #收货地址
    url(r'^user_address/',views.user_address,name='user_address'),

]

fresh_shop/cart/models.py
from django.db import models

from goods.models import Goods
from user.models import User


class ShoppingCart(models.Model):
    """
    购物车
    """
    user = models.ForeignKey(User, verbose_name='用户', on_delete=models.CASCADE)
    goods = models.ForeignKey(Goods, verbose_name='商品', on_delete=models.CASCADE)
    nums = models.IntegerField(default=0, verbose_name='数量')
    add_time = models.DateTimeField(auto_now_add=True, verbose_name='添加时间')
    is_select = models.BooleanField(default=True)

    class Meta:
        db_table = 'f_shopping_cart'

fresh_shop/cart/views.py
from django.shortcuts import render
from django.http import JsonResponse

from goods.models import Goods
from cart.models import ShoppingCart
from user.models import UserAddress


def add_cart(request):
    if request.method == 'POST':
        #加入到购物车，需判断用户是否登录
        #如果登录，加入到购物车中的数据，其实就是加入到数据库中购物车表中

        #如果登录，加入到购物车中的数据存储到session中
        #如果没有登录，则加入到购物车的数据是加入到session中
        # session中存储数据，商品id，商品数量，商品的选择状态
        #如果登录，则把session中的数据同步到数据库中(中间价同步数据)
        #1.获取商品id和商品数量
        goods_id = int(request.POST.get('goods_id'))
        goods_num = int(request.POST.get('goods_num'))

        #2.组装存到session中的数据格式
        goods_list = [goods_id,goods_num,1]
        if request.session.get('goods'):
            #说明session中存储了加入到购物车的商品信息
            #判断当前加入到购物车中的数据，是否已经存在于session中
            #如果不存在，
            flag = 0
            session_goods = request.session['goods']
            for goods in session_goods:
                #判断如果加入到购物车中，已经存在session，则修改
                if goods[0] == goods_id:
                    goods[1] = int(goods[1]) + int(goods_num)
                    flag = 1
            if not flag:

                #如果不存在 则添加
                session_goods.append(goods_list)
            request.session['goods'] = session_goods
            goods_count = len(session_goods)


        else:
            data = []
            data.append(goods_list)
            request.session['goods'] = data
            goods_count = 1

        return JsonResponse({'code': 200, 'msg': '请求成功','goods_count':goods_count})

def cart(request):
    if request.method == 'GET':
        #如果没有登录，则从session中获取商品的信息
        #如果登录，还是从session中获取数据（保证数据库中的商品和session中商品一致）
        session_goods = request.session.get('goods')
        if session_goods:
            #获取session中所有商品的id值
            goods_all = []
            for goods in session_goods:
                cart_goods = Goods.objects.filter(pk=goods[0]).first()
                goods_number = goods[1]
                total_price = goods[1] * cart_goods.shop_price
                goods_all.append([cart_goods,goods_number,total_price])

            #前台需要商品信息，商品的个数，商品的总价
            #后台返回结构[[goods objects,number,total_price],[goods_objects]]
            #获取商品对象
            # goods = Goods.objects.filter(pk__in=goods_ids).all()
        else:
            goods_all = ''
        return render(request,'cart.html',{'goods_all':goods_all})


def place_order(request):
    if request.method == 'GET':
        #获取当前登录系统的user_id
        user_id = request.session.get('user_id')
        #获取当前勾选的商品用于下单
        carts = ShoppingCart.objects.filter(user_id=user_id,
                                            is_select=True)

        for cart in carts:
            #给每一个购物车商品对象添加一个total_price属性，用于存储总价
            cart.total_price = int(cart.nums) \
                               * int(cart.goods.shop_price)

        addresses = UserAddress.objects.filter(user_id=user_id)
        return render(request,'place_order.html',{'carts':carts,'addresses':addresses})

def f_price(request):
    """
    返回购物车或session中商品的价格和总价
    {key:[[id1,price1],[id2,price2]],key2:total price}
    """
    if request.method == 'GET':
        user_id = request.session.get('user_id')
        if user_id:
            #获取当前登录系统的用户的购物车中的数据
            carts = ShoppingCart.objects.filter(user_id=user_id)
            cart_data = {}
            cart_data['goods_price'] = [(cart.goods_id,
                                         cart.nums * cart.goods.shop_price)
                                        for cart in carts]
            all_price = 0
            #总价格
            for cart in carts:
                if cart.is_select:
                    all_price += cart.nums * cart.goods.shop_price
            cart_data['all_price'] = all_price
        else:
            #获取session中所有的商品信息，[id,num,is_select]
            session_goods = request.session.get('goods')
            #返回数据结构,{'goods_price':[[id1,price1],[id2,price2]...]}
            cart_data = {}
            data_all = []
            #计算总价
            all_price = 0
            for goods in session_goods:
                data = []
                data.append(goods[0])
                g = Goods.objects.get(pk=goods[0])
                data.append(int(goods[1]) * g.shop_price)
                #生成的data为：[id1,price1]
                data_all.append(data)
                #判断如果商品勾选了才计算总价
                if goods[2]:
                    all_price += int(goods[1]) * g.shop_price
            cart_data['goods_price'] = data_all
            cart_data['all_price'] = all_price
        return JsonResponse({'code':200,'cart_data':cart_data,'all_price':all_price})

def cart_count(request):
    if request.methon == 'GET':
        #判断购物车中商品的个数
        user_id = request.session.get('user_id')
        #当前购物车中的商品数量
        if user_id:
            #如果用户登录，则获取购物车表中的商品个数
            count = ShoppingCart.objects.filter(user_id=user_id).count()
        else:
            #如果用户没有登录，则获取session中商品的个数
            session_goods = request.session.get('goods')
            count = len(session_goods)
        return JsonResponse({'code':200,'msg':'请求成功','count':count})

def change_goods_num(request):
    if request.method == 'POST':
        #修改购物车中商品的个数
        #1.先判断用户是否登录，如果没有登录，则修改session中的值
        #2.如果用户已经登录，需要判断当前修改的商品是否存在于session中，
        # 如果存在则修改session，不存在就修改购物车的表
        #获取修改的商品id,商品个数，商品选择状态
        goods_id = request.POST.get('goods_id')
        goods_num = int(request.POST.get('goods_num'))
        is_select = int(request.POST.get('is_select'))

        user_id = request.session.get('user_id')

        #先判断要修改的商品是否存在于session中，如果存在则修改session中的商品个数和选择状态
        session_goods = request.session.get('goods')
        #goods的结构为：[id1,num,is_select]
        if session_goods:
            for goods in session_goods:
                if goods_id == goods[0]:
                    #修改session中商品的个数和选择状态
                    goods[1] = goods_num
                    goods[2] = is_select
            request.session['goods'] = session_goods
        #如果用户登录了，则需要在购物车中修改数据，因为session中的商品有可能不在购物车表中
        if user_id:
            #修改购物车中商品的个数
            ShoppingCart.objects.filter(user_id=user_id,goods_id=goods_id).update(nums=goods_num,
                                                                                  is_select=is_select)
        return JsonResponse({'code':200,'msg':'请求成功'})

def del_goods(request):
    if request.method == 'POST':
        #删除购物车中的商品
        #如果用户没有登录，删除session中的值，如果用户登录则删除数据库中的数据
        #获取商品
        goods_id = request.POST.get('goods_id')
        user_id = request.session.get('user_id')


        session_goods = request.session.get('goods')


        if user_id:
            request.session.flush(session_goods)
            ShoppingCart.objects.filter(user_id=user_id,goods_id=goods_id).delete()

    return render(request,'cart.html')

fresh_shop/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    {% block css %}
    {% endblock %}


    {% block js %}
    {% endblock %}
</head>
<body>
    {% block header %}
    {% endblock %}

    {% block search %}
    {% endblock %}

    {% block content %}
    {% endblock %}


    {% block bottom %}
    {% endblock %}

    {% block endjs %}
    {% endblock %}
</body>
</html>

fresh_shop/templates/base_main.html
{% extends 'base.html' %}



{% block css %}
	{% load static %}
		<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
{% endblock %}

{% block js %}
	{% load static %}
	<script type="text/javascript">
		<!-- 获取用户的登录用户名 -->
		$.get('/user/is_login',function(data){
			if(data.code == '200'){
				$('.login_info em').html(data.username)
				<!--展示当前用户信息-->
				$('.login_info').show()
				<!--隐藏登录注册按钮-->
				$('.login_btn').remove()
			}
		})
		<!--获取购物车中的商品个数-->
		$.get('/cart/cart_count/', function(data){
			if(data.code == '200'){
				$('#show_count').html(data.count)
				$('.total_count em').html(data.count)
			}
		})
	</script>
{% endblock %}




{% block header %}
	<body>
		<div class="header_con">
			<div class="header">
				<div class="welcome fl">欢迎来到天天生鲜!</div>
				<div class="fr">
					{% if user.id %}
						<div class="login_info fl" style="display:block;">
							欢迎您：<em>{{ user.username }}</em>
							<span>|</span>
							<a href="{% url 'user:logout' %}">注销</a>
						</div>
					{% else %}
						<div class="login_btn fl">
							<a href="{% url 'user:login' %}">登录</a>
							<span>|</span>
							<a href="{% url 'user:register' %}">注册</a>
						</div>
					{% endif %}
					<div class="user_link fl">
						<span>|</span>
						<a href="{% url 'user:user_center_order' %}">用户中心</a>
						<span>|</span>
						<a href="{% url 'cart:cart' %}">我的购物车</a>
						<span>|</span>
						<a href="{% url 'order:user_order' %}">我的订单</a>
					</div>
				</div>
			</div>
		</div>
{% endblock %}

{% block search %}
    <div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cart:cart' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ carts | length }}</div>
		</div>
    </div>

{% endblock %}

{% block bottom %}
    <div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
{% endblock %}

{% block endjs %}
	<script type="text/javascript" src="js/slideshow.js"></script>
	<script type="text/javascript">
		BCSlideshow('focuspic');
		var oFruit = document.getElementById('fruit_more');
		var oShownum = document.getElementById('show_count');

		var hasorder = localStorage.getItem('order_finish');

		if(hasorder)
		{
			oShownum.innerHTML = '2';
		}

		oFruit.onclick = function(){
			window.location.href = 'list.html';
		}
	</script>
{% endblock %}

fresh_shop/templates/cart.html
{% extends 'base_main.html' %}

{% block title %}
	购物车
{% endblock %}


{% block content %}

	<div class="total_count">全部商品<em></em>件</div>
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>
	{% if goods_all %}
		{% for goods in goods_all %}
			<ul class="cart_list_td clearfix">
				<li class="col01"><input type="checkbox" name="{% if goods.2 %}" checked {% endif %} onchange="change_select({{ goods.0.id }})"></li>
				<input type="hidden" {% if goods.2 %} value="1" {% else %} value="0" {% endif %} id="goods_select_{{ goods.0.id }}">
				<li class="col02"><img src="/media/{{ goods.0.goods_front_image }}"></li>
				<li class="col03">{{ goods.0.name }}<br><em>{{ goods.0.shop_price }}元/500g</em></li>
				<li class="col04">500g</li>
				<li class="col05">{{ goods.0.shop_price }}元</li>
				<li class="col06">
					<div class="num_add">
                        <a href="javascript:;" class="add fl" onclick="add_cart_num({{ goods.0.id }});">+</a>
                        <input type="text" class="num_show fl" value="{{ goods.1 }}" id="goods_num_{{ goods.0.id }}">
                        <a href="javascript:;" class="minus fl" onclick="sub_cart_num({{ goods.0.id }});">-</a>
                    </div>
				</li>
				<li class="col07" id="goods_{{ goods.0.id }}">{{ goods.2 }}元</li>
				<li class="col08"><a href="{% url 'cart:del_goods' %}">删除</a></li>
			</ul>
		{% endfor %}
	{% endif %}

	<!--定义修改购物车中数量，勾选状态等操作-->
	{% csrf_token %}
	<script>
		<!--刷新商品的价格-->
		$.get('/cart/f_price/',function(data){
			if(data.code == '200'){
				for(var i=0;i<data.cart_data.goods_price.length;i++){
					price = data.cart_data.goods_price[i][1] + '元'
					$('#goods_' + data.cart_data.goods_price[i][0]).html(price)
				}
				$('#total_price em').html(data.cart_data.all_price + '元')
			}
		})

		<!--增加商品的个数-->
		function add_cart_num(goods_id){
			<!--获取商品的个数-->
			var goods_num = $('#goods_num_' + goods_id).val()
			<!--TODO暂且不判断添加商品是否超过库存-->
			$('#goods_num_' + goods_id).val(parseInt(goods_num) + 1)
			change_cart_num(goods_id)
		}

		<!--减少商品个数-->
		function sub_cart_num(goods_id){
			<!--获取商品个数-->
			var goods_num = $('#goods_num' + goods_id).val()
			<!--判断减少商品的数量，不能小于1-->
			num = parseInt(goods_num) - 1
			if(num > 0){
				$('#goods_num_' + goods_id).val(num)
				change_cart_num(goods_id)
			}
		}

		<!--修改商品的选择状态-->
		function change_select(goods_id){
			goods_select = $('#goods_select_' + goods_id).val()
			if(goods_select == '1'){
				$('#goods_select_' + goods_id).val('0')
			}else{
				$('#goods_select_' + goods_id).val('1')
			}
			change_cart_num(goods_id)
		}

		<!--修改商品的个数，选择状态-->
		function change_cart_num(goods_id){
			var csrf = $('input[name="csrfmiddlewaretoken"]').val()
			<!--获取商品的个数-->
			var goods_num = $('#goods_num_' + goods_id).val()
			<!--获取商品的选择状态-->
			var is_select = $('#goods_select_' + goods_id).val()
			$.ajax({
				url:'/cart/change_goods_num/',
				data:{'goods_id':goods_id,'goods_num':goods_num,'is_select':is_select},
				type:'POST',
				dataType:'json',
				headers:{'X-CSRFToken':csrf},
				success:function(data){
					console.log(data)
				},
				error:function(data){
					alert('请求失败')
				}
			})
		}
	</script>

	<ul class="settlements">
		<li class="col01"><input type="checkbox" name="" checked=""></li>
		<li class="col02">全选</li>
		<li class="col03" id="total_price">合计(不含运费)：<span>¥</span><em>元</em><br></li>
		<li class="col04"><a href="{% url 'cart:place_order' %}">去结算</a></li>
	</ul>

{% endblock %}

fresh_shop/templates/index.html
{% extends 'base_main.html' %}

{% block title %}
天天生鲜-首页
{% endblock %}

{% block js %}
	{% load static %}
		<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock %}


{% block content %}

	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
			<li><a href="#model01" class="fruit">新鲜水果</a></li>
			<li><a href="#model02" class="seafood">海鲜水产</a></li>
			<li><a href="#model03" class="meet">猪牛羊肉</a></li>
			<li><a href="#model04" class="egg">禽类蛋品</a></li>
			<li><a href="#model05" class="vegetables">新鲜蔬菜</a></li>
			<li><a href="#model06" class="ice">速冻食品</a></li>
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
				<li><img src="{% static 'images/slide.jpg' %}" alt="幻灯片"></li>
				<li><img src="{% static 'images/slide02.jpg' %}" alt="幻灯片"></li>
				<li><img src="{% static 'images/slide03.jpg' %}" alt="幻灯片"></li>
				<li><img src="{% static 'images/slide04.jpg' %}" alt="幻灯片"></li>
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			<a href="#"><img src="{% static 'images/adv01.jpg' %}"></a>
			<a href="#"><img src="{% static 'images/adv02.jpg' %}"></a>
		</div>
	</div>
	{% for key,value in goods_dict.items %}


	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model01">{{ key }}</h3>
			<!--<div class="subtitle fl">-->
				<!--<span>|</span>-->
				<!--<a href="#">鲜芒</a>-->
				<!--<a href="#">加州提子</a>-->
				<!--<a href="#">亚马逊牛油果</a>-->
			<!--</div>-->
			<a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/media/{{value.0.category.category_front_image}}"></div>
			<ul class="goods_list fl">
				{% for goods in value %}
					<li>
						<h4><a href="{% url 'goods:detail' goods.id %}">{{ goods.name }}</a></h4>
						<a href="{% url 'goods:detail' goods.id %}"><img src="/media/{{ goods.goods_front_image }}"></a>
						<div class="prize">{{ goods.shop_price }}</div>
					</li>
				{% endfor %}


			</ul>
		</div>
	</div>
	{% endfor %}
{% endblock %}

fresh_shop/templates/user_center_info.html
{% extends 'base_main.html' %}

{% block title %}
	天天生鲜—用户中心
{% endblock %}

{% block content %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user_center_order' %}" class="active">· 个人信息</a></li>
				<li><a href="{% url 'order:user_order' %}">· 全部订单</a></li>
				<li><a href="{% url 'order:user_order_site' %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{ user.username }}</li>
							<li><span>联系方式：</span>
								{% if user.mobile %}
									{{ user.mobile }}
								{% else %}
									暂无
								{% endif %}

							</li>
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
				<li>
					<!--<a href="detail.html"><img src="images/goods/goods003.jpg"></a>-->
					<!--<h4><a href="detail.html">大兴大棚草莓</a></h4>-->
					<!--<div class="operate">-->
						<!--<span class="prize">￥16.80</span>-->
						<!--<span class="unit">16.80/500g</span>-->
						<!--<a href="#" class="add_goods" title="加入购物车"></a>-->
					<!--</div>-->
				</li>


			</ul>
		</div>
		</div>
	</div>

{% endblock %}

fresh_shop/templates/user_center_order.html
{% extends 'base_main.html' %}

{% block title %}
	天天生鲜—订单
{% endblock %}

{% block content %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user_center_order' %}">· 个人信息</a></li>
				<li><a href="{% url 'order:user_order' %}" class="active">· 全部订单</a></li>
				<li><a href="{% url 'order:user_order_site' %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
			{% csrf_token %}
			{% for o_info in order_info %}
				<h3 class="common_title2">全部订单</h3>
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ o_info.add_time | date:'Y-m-d h:m:s' }}</li>
					<li class="col02">订单号：{{ o_info.order_sn }}</li>
					<li class="col02 stress">
						{% for status in order_status %}
							{% if status.0 == o_info.pay_status %}
								{{ status.1 }}
							{% endif %}
						{% endfor %}
					</li>
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
								{% for order_goods in o_info.goods.all %}
									<ul class="order_goods_list clearfix">
										<li class="col01"><img src="/media/{{ order_goods.goods.goods_front_image }}"></li>
										<li class="col02">{{ order_goods.goods.name }}<em>{{ order_goods.goods.shop_price }}元/500g</em></li>
										<li class="col03">{{ order_goods.goods_nums }}</li>
										<li class="col04">{{ order_goods.goods.shop_price }}元</li>
									</ul>
								{% endfor %}

							</td>
							<td width="15%">{{ o_info.order_mount }}元</td>
							<td width="15%">
								{% for status in order_status %}
									{% if status.0 == o_info.pay_status %}
										{{ status.1 }}
									{% endif %}
								{% endfor %}
							</td>
							<td width="15%">
								<a href="#" class="oper_btn">
									{% if o_info.pay_status == 'PAYING' %}
										<a href="#">去付款</a>
									{% endif %}
									{% if o_info.pay_status == 'TRADE_SUCCESS' %}
										成功
									{% endif %}
								</a>
							</td>
						</tr>
					</tbody>
				</table>
			{% endfor %}
				
				<div class="pagenation">
					{% if page.has_previous %}
						<a href="{% url 'order:user_order' %}?page={{ page.previous_page_number }}">上一页</a>
					{% endif %}
					<a href="#" class="active">1</a>
					{% for i in page.paginator.page_range %}
						<a href="{% url 'order:user_order' %}?page={{ i }}">{{ i }}</a>
					{% endfor %}
					{% if page.has_next %}
						<a href="{% url 'order:user_order' %}?page={{ page.next_page_number }}">下一页</a>
					{% endif %}
				</div>
		</div>
	</div>
{% endblock %}

fresh_shop/templates/user_center_site.html
{% extends 'base_main.html' %}

{% block title %}
	天天生鲜—用户中心
{% endblock %}


{% block content %}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user_center_order' %}">· 个人信息</a></li>
				<li><a href="{% url 'order:user_order' %}">· 全部订单</a></li>
				<li><a href="{% url 'order:user_order_site' %}" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
						{% for user_address in user_addresses %}
							<dd>{{ user_address.address }}
								({{ user_address.signer_name }}收)
								{{ user_address.signer_mobile }}
							</dd>
						{% endfor %}
					</dl>
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form action="{% url 'user:user_address' %}" method="post">
						{% csrf_token %}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="signer_name">
							{{ form.errors.signer_name }}
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="address"></textarea>
							{{ form.errors.signer_name }}
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="signer_postcode">
							{{ form.errors.signer_postcode }}
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="signer_mobile">
							{{ form.errors.signer_mobile }}
						</div>

						<input type="submit" name="" value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>



{% endblock %}